### ISSUE TITLE
Fails to build on Ubuntu 24.04

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/SPIRV-LLVM-Translator#3517]
Trying to build with Ubuntu 24.04

`CXX=/usr/bin/clang++-22 CC=/usr/bin/clang-22 cmake .. -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/lib/llvm-22/lib/cmake/llvm`

and when I try to build I get hit with 

```
/usr/bin/clang++-22 -DLLVM_SPIRV_BACKEND_TARGET_PRESENT -D_GLIBCXX_USE_CXX11_ABI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-22/include -I/SPIRV-LLVM-Translator/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wno-pass-failed -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -g -std=gnu++17 -fcolor-diagnostics -fno-exceptions -funwind-tables -MD -MT tools/llvm-spirv/CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o -MF tools/llvm-spirv/CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o.d -o tools/llvm-spirv/CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o -c /SPIRV-LLVM-Translator/tools/llvm-spirv/llvm-spirv.cpp
/SPIRV-LLVM-Translator/tools/llvm-spirv/llvm-spirv.cpp:781:50: error: non-const lvalue reference to type 'DenseMap<llvm::StringRef, llvm::cl::Option *>' cannot bind to a value of unrelated type 'StringMap<Option *>'
  781 |   DenseMap<llvm::StringRef, llvm::cl::Option *> &RegisteredOptions =
      |                                                  ^
  782 |       llvm::cl::getRegisteredOptions();
```

not knowledgeable about the code enough to grasp what is going on here or the correct fix
